import { Poppins } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const Poppins_ = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-caption",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(Poppins_.variable)}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
